/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Fraunces', 'Noto Serif SC', 'serif'],
        body: ['DM Sans', 'Noto Sans SC', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        serifcn: ['Noto Serif SC', 'Fraunces', 'serif'],
      },
      colors: {
        brand: {
          50: '#fff5f7',
          100: '#ffe8ec',
          200: '#ffd1d9',
          300: '#ffb3c1',
          400: '#ff8fa3',
          500: '#ff6b81',
          600: '#e54d65',
          700: '#be123c',
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#ff8fa3",
          "primary-content": "#ffffff",
          "secondary": "#ff6b81",
          "secondary-content": "#ffffff",
          "accent": "#ffb3c1",
          "accent-content": "#1a1a1a",
          "neutral": "#1a1a1a",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#fafafa",
          "base-300": "#f5f5f5",
          "base-content": "#1a1a1a",
          "info": "#60a5fa",
          "info-content": "#ffffff",
          "success": "#34d399",
          "success-content": "#1a1a1a",
          "warning": "#fbbf24",
          "warning-content": "#1a1a1a",
          "error": "#ff6b81",
          "error-content": "#ffffff",
        },
      },
      {
        dark: {
          "primary": "#ffb3c1",
          "primary-content": "#0a0a0a",
          "secondary": "#ff8fa3",
          "secondary-content": "#0a0a0a",
          "accent": "#ffd1d9",
          "accent-content": "#0a0a0a",
          "neutral": "#f5f5f5",
          "neutral-content": "#0a0a0a",
          "base-100": "#0a0a0a",
          "base-200": "#141414",
          "base-300": "#1c1c1c",
          "base-content": "#f5f5f5",
          "info": "#60a5fa",
          "info-content": "#0a0a0a",
          "success": "#34d399",
          "success-content": "#0a0a0a",
          "warning": "#fbbf24",
          "warning-content": "#0a0a0a",
          "error": "#ff8fa3",
          "error-content": "#0a0a0a",
        },
      },
    ],
  },
}
