/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#FF6B9D",
          "primary-content": "#ffffff",
          "secondary": "#C44D8B",
          "secondary-content": "#ffffff",
          "accent": "#7C3AED",
          "accent-content": "#ffffff",
          "neutral": "#1e1e2e",
          "neutral-content": "#f5f5f5",
          "base-100": "#fafafa",
          "base-200": "#f0f0f5",
          "base-300": "#e5e5ec",
          "base-content": "#1a1a2e",
          "info": "#60a5fa",
          "info-content": "#ffffff",
          "success": "#34d399",
          "success-content": "#ffffff",
          "warning": "#fbbf24",
          "warning-content": "#1a1a2e",
          "error": "#f87171",
          "error-content": "#ffffff",
        },
      },
      {
        dark: {
          "primary": "#FF6B9D",
          "primary-content": "#ffffff",
          "secondary": "#C44D8B",
          "secondary-content": "#ffffff",
          "accent": "#A78BFA",
          "accent-content": "#ffffff",
          "neutral": "#1a1a2e",
          "neutral-content": "#eeeeee",
          "base-100": "#0a0a0f",
          "base-200": "#12121a",
          "base-300": "#1e1e2e",
          "base-content": "#eeeeee",
          "info": "#60a5fa",
          "info-content": "#0a0a0f",
          "success": "#34d399",
          "success-content": "#0a0a0f",
          "warning": "#fbbf24",
          "warning-content": "#0a0a0f",
          "error": "#f87171",
          "error-content": "#0a0a0f",
        },
      },
    ],
  },
}
