/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ['Fraunces', 'Noto Serif SC', 'serif'],
        body: ['DM Sans', 'Noto Sans SC', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        serifcn: ['Noto Serif SC', 'Fraunces', 'serif'],
      },
      colors: {
        violet: {
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
        },
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#8b5cf6",
          "primary-content": "#ffffff",
          "secondary": "#7c3aed",
          "secondary-content": "#ffffff",
          "accent": "#8b5cf6",
          "accent-content": "#ffffff",
          "neutral": "#1a1a1a",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#fafafa",
          "base-300": "#f5f5f5",
          "base-content": "#1a1a1a",
          "info": "#60a5fa",
          "info-content": "#ffffff",
          "success": "#34d399",
          "success-content": "#1a1a1a",
          "warning": "#fbbf24",
          "warning-content": "#1a1a1a",
          "error": "#8b5cf6",
          "error-content": "#ffffff",
        },
      },
      {
        dark: {
          "primary": "#a78bfa",
          "primary-content": "#0a0a0a",
          "secondary": "#8b5cf6",
          "secondary-content": "#0a0a0a",
          "accent": "#a78bfa",
          "accent-content": "#0a0a0a",
          "neutral": "#f5f5f5",
          "neutral-content": "#0a0a0a",
          "base-100": "#0a0a0a",
          "base-200": "#141414",
          "base-300": "#1c1c1c",
          "base-content": "#f5f5f5",
          "info": "#60a5fa",
          "info-content": "#0a0a0a",
          "success": "#34d399",
          "success-content": "#0a0a0a",
          "warning": "#fbbf24",
          "warning-content": "#0a0a0a",
          "error": "#a78bfa",
          "error-content": "#0a0a0a",
        },
      },
    ],
  },
}
