import { describe, expect, it } from 'vitest'
import {
  categorizeCommits,
  formatReleaseNotes,
  parseArgs,
  parseConventionalCommit,
  parseGitLog,
  selectPreviousTag,
  semverTagValue
} from './release-notes.mjs'

describe('release notes generator', () => {
  it('parses command line options', () => {
    expect(
      parseArgs(['--from', 'v1.0.0', '--to', 'HEAD', '--version', '1.1.0', '--output', 'notes.md'])
    ).toEqual({
      from: 'v1.0.0',
      to: 'HEAD',
      version: '1.1.0',
      output: 'notes.md',
      help: false
    })
  })

  it('parses conventional and breaking commits', () => {
    expect(parseConventionalCommit('feat(auth): improve OAuth callback')).toEqual({
      type: 'feat',
      scope: 'auth',
      breaking: false,
      subject: 'improve OAuth callback'
    })
    expect(parseConventionalCommit('fix!: change deployment contract')).toEqual({
      type: 'fix',
      scope: undefined,
      breaking: true,
      subject: 'change deployment contract'
    })
  })

  it('selects only semantic version tags', () => {
    expect(semverTagValue('v1.2.1')).toBe('1.2.1')
    expect(semverTagValue('test')).toBeUndefined()
    expect(selectPreviousTag(['v1.2.1', 'test', 'v1.0.0'], 'v1.2.1')).toBe('v1.0.0')
  })

  it('groups commits and formats linked release notes', () => {
    const fields = [
      'a'.repeat(40),
      'feat(auth): improve OAuth callback',
      'A',
      'a@example.com',
      'b'.repeat(40),
      'fix: preserve SPA callback route',
      'B',
      'b@example.com',
      'c'.repeat(40),
      'security: validate OAuth state',
      'C',
      'c@example.com',
      'd'.repeat(40),
      'docs: explain Cloudflare setup',
      'D',
      'd@example.com',
      'e'.repeat(40),
      'chore: update dependencies',
      'E',
      'e@example.com',
      'f'.repeat(40),
      'miscellaneous maintenance',
      'F',
      'f@example.com',
      '0'.repeat(40),
      'release: v1.0.0',
      'G',
      'g@example.com',
      '1'.repeat(40),
      'feat: 新增跳一跳小游戏页面与导航入口',
      'H',
      'h@example.com',
      '2'.repeat(40),
      'fix: retire jump game',
      'I',
      'i@example.com'
    ]
    const commits = parseGitLog(
      fields.map((field, index) => field + (index % 4 === 3 ? '\x1e' : '\x1f')).join('')
    )
    const grouped = categorizeCommits(commits)

    expect(grouped.get('Features')).toHaveLength(1)
    expect(grouped.get('Bug Fixes')).toHaveLength(1)
    expect(grouped.get('Security')).toHaveLength(1)
    expect(grouped.get('Documentation')).toHaveLength(1)
    expect(grouped.get('Maintenance')).toHaveLength(1)
    expect(grouped.get('Other Changes')).toHaveLength(1)

    const notes = formatReleaseNotes({
      packageName: 'Bangmio',
      version: '1.1.0',
      from: 'v1.0.0',
      commits,
      repositoryUrl: 'https://github.com/sparkmio/Bangmio'
    })
    expect(notes).toContain('## Bangmio v1.1.0')
    expect(notes).toContain('### Security')
    expect(notes).toContain('improve OAuth callback')
    expect(notes).toContain('https://github.com/sparkmio/Bangmio/commit/aaaaaaaa')
    expect(notes).toContain('Generated by scripts/release-notes.mjs')
    expect(notes).not.toContain('release: v1.0.0')
    expect(notes).not.toContain('跳一跳小游戏')
    expect(notes).not.toContain('jump game')
  })
})
